import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.plugin.compose")
}

// Generated by the repository maintenance command; metadata remains authoritative.
val metadata = Properties().apply { file("../metadata.properties").inputStream().use { load(it) } }
android {
    namespace = "com.aitiotekt.webauthndiagnosis"
    compileSdk = 36
    defaultConfig {
        applicationId = metadata.getProperty("applicationId")
        minSdk = 28
        targetSdk = 36
        versionCode = metadata.getProperty("versionCode").toInt()
        versionName = metadata.getProperty("versionName")
        buildConfigField("String", "TEST_URL", "\"${metadata.getProperty("testUrl")}\"")
    }
    signingConfigs {
        create("upload") {
            System.getenv("ANDROID_KEYSTORE_PATH")?.let { storeFile = file(it) }
            storePassword = System.getenv("ANDROID_KEYSTORE_PASSWORD")
            keyAlias = System.getenv("ANDROID_KEY_ALIAS")
            keyPassword = System.getenv("ANDROID_KEY_PASSWORD")
        }
    }
    buildTypes {
        release {
            signingConfig = signingConfigs.getByName("upload")
            isMinifyEnabled = false
        }
    }
    buildFeatures { compose = true; buildConfig = true }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    lint {
        abortOnError = true
        warningsAsErrors = true
        // Dependency currency is reviewed separately, not a time-dependent CI
        // failure. API 36 is intentional until API 37 behavior is device-tested.
        disable += setOf("GradleDependency", "AndroidGradlePluginVersion", "OldTargetApi")
    }
}

dependencies {
    implementation(platform("androidx.compose:compose-bom:2026.02.01"))
    implementation("androidx.activity:activity-compose:1.12.4")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.lifecycle:lifecycle-viewmodel-compose:2.10.0")
    implementation("androidx.lifecycle:lifecycle-runtime-compose:2.10.0")
    implementation("androidx.browser:browser:1.10.0")
    implementation("androidx.credentials:credentials:1.6.0")
    debugImplementation("androidx.compose.ui:ui-tooling")
    testImplementation("junit:junit:4.13.2")
}

// A release must never silently use a debug key or produce an unsigned AAB.
tasks.matching { it.name == "validateSigningRelease" }.configureEach {
    doFirst {
        listOf("ANDROID_KEYSTORE_PATH", "ANDROID_KEYSTORE_PASSWORD", "ANDROID_KEY_ALIAS", "ANDROID_KEY_PASSWORD").forEach {
            check(!System.getenv(it).isNullOrBlank()) { "Missing Android upload signing configuration: $it" }
        }
    }
}
